name: Build Android APK/AAB in cloud

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Java (Android/Gradle)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses & install platforms/tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" \
                     "platforms;android-33" "build-tools;33.0.2" \
                     "platforms;android-34" "build-tools;34.0.0"

      - name: Install Bubblewrap CLI
        run: npm i -g @bubblewrap/cli

      # >>> KEY STEP: preconfigure Bubblewrap so it never prompts
      - name: Configure Bubblewrap paths (no prompts)
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
        run: |
          # Some actions set ANDROID_HOME; ensure ANDROID_SDK_ROOT is set too
          if [ -z "${ANDROID_SDK_ROOT}" ] && [ -n "${ANDROID_HOME}" ]; then
            echo "ANDROID_SDK_ROOT=${ANDROID_HOME}" >> $GITHUB_ENV
            export ANDROID_SDK_ROOT="${ANDROID_HOME}"
          fi
          mkdir -p "${HOME}/.bubblewrap"
          cat > "${HOME}/.bubblewrap/config.json" <<EOF
          {
            "jdkPath": "${JAVA_HOME}",
            "androidSdkPath": "${ANDROID_SDK_ROOT:-$ANDROID_HOME}",
            "analyticsEnabled": false
          }
          EOF
          echo "=== ~/.bubblewrap/config.json ==="
          cat "${HOME}/.bubblewrap/config.json"

      - name: Create TWA project from your live PWA (non-interactive)
        run: |
          mkdir twa && cd twa
          # With config.json present, Bubblewrap won't ask any questions.
          bubblewrap init \
            --manifest=https://ahadi332211.github.io/quran-anywhere/manifest.json \
            --skipPwaValidation \
            --packageId=com.ahadi.qurananywhere \
            --name="Quran Anywhere" \
            --launcherName="Quran" \
            --appVersionName=1.0.0 \
            --appVersionCode=1
          echo "Created TWA project:"
          ls -la

      - name: Build unsigned AAB/APK (release)
        working-directory: ./twa
        run: |
          chmod +x ./gradlew
          ./gradlew --version
          ./gradlew :app:bundleRelease :app:assembleRelease --stacktrace --no-daemon

      - name: Upload artifacts (AAB/APK)
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: |
            twa/app/build/outputs/bundle/release/*.aab
            twa/app/build/outputs/apk/release/*.apk
